spring:
  datasource:
    url: jdbc:h2:./data/sidereal_confluence;AUTO_SERVER=TRUE
    username: sidereal-confluence
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  session:
    jdbc:
      initialize-schema: always

auth.cookie.hmac-key: MkNpO9WT9bXn+pySHrAj1HVLN4p9l5VXdrvGYR8st+FUThbZjPbfQK/LjhAFcyUwWNMRifX+4rqiskoRINV7rR6zrd55UNFL3DkprcKIgyZy4gB6pzeJ+/tD+ruMp0PhpDtV7WqjelUNSMtaUjF6iL+AbonOqhrx+RYvgZtaeuAmBKLYHceOu9B/+rTT+paui8OESIwfm2AiJIV3qMvTTIOdWjKIyZicoq6T8g==